### ISSUE TITLE
Error using cropRectified

### ISSUE THREAD

**Issue by pabloni98** [johnvorhies/LightField-CameraArrayCalibration#2]
Hello John.

I am trying out your code to calibrate a camera array for a project I'm working on that uses light fields to remove occlusions. I'm currently working with a set of 5 images. I was able to use createTransformMatrixLF_Center and rectifyImagesViaTransforms correctly. However, when I try to use cropRectified, it displays the figure with the center image, and then after a long time I get the following error:

```
Error using parseInputsOverTwo
Expected input number 2, RECT, to be a vector.

Error in images.internal.crop.parseInputsOverTwo>validateRectangle (line 173)
validateattributes(rect,{'numeric'},{'real','vector'}, ...

Error in images.internal.crop.parseInputsOverTwo (line 54)
            validateRectangle(spatial_rect,2);

Error in imcrop (line 104)
        images.internal.crop.parseInputsOverTwo(varargin{:});

Error in cropRectified (line 12)
        I = imcrop(I,rect);
```
Looks like rect is not a valid parameter for imcrop. Do you know why this is the case and how I can fix it? The cropped images are never written to the croppedDir I specify in the function call. 

Thanks for your time.

**Comment by johnvorhies** [comment]
When the figure pops up, are you selecting an area to crop? It does require
user input.

**Comment by pabloni98** [comment]
Hello John,
Yes, I was making that mistake. I am new to MATLAB and I had never used imcrop before. I'm sorry if I caused you trouble.
Thank you.
